#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# Source files
source $ZDOTDIR/key-bindings.zsh
source $ZDOTDIR/completion.zsh
# eval "`pip completion --zsh`"


