#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
# eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# Source files
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
# eval "`pip completion --zsh`"


