#!/bin/sh

alias j='zi'
alias f='zi'
# alias h='cd ~/'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors for Arch Linux
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
# alias remarkable_ssh='ssh root@10.11.99.1'
# alias restream='restream -p'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
# alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
# alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
# alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

# alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

# alias m="git checkout master"
# alias s="git checkout stable"


# if [[ $TERM == "xterm-kitty" ]]; then
#   alias ssh="kitty +kitten ssh"
# fi
#
# case "$(uname -s)" in
#
# Darwin)
# 	# echo 'Mac OS X'
# 	alias ls='ls -G'
# 	;;
#
# Linux)
# 	alias ls='ls --color=auto'
# 	;;
#
# CYGWIN* | MINGW32* | MSYS* | MINGW*)
# 	# echo 'MS Windows'
# 	;;
# *)
# 	# echo 'Other OS'
# 	;;
# esac
#




# General Aliases

alias tmux="tmux -u"
alias please="sudo"
alias upd="sudo pacman -Syyu"
alias pls="sudo"
# alias cat="bat"
alias nv="nvim"
# alias gcc="gcc -lcs50"
# alias clang="clang -lcs50"
# alias clang-10="clang-10 -lcs50"
alias doom="~/.emacs.d/bin/doom"

# replace ls with exa
# alias ls="exa -l --icons --group-directories-first"
alias la="exa -la --icons --group-directories-first"
alias lls=ls
alias l=la

# replace ps with procs
alias ps="procs"

# replace find with fd
# alias find="fd"

# replace grep with ripgrep
alias grep="rg"

# fasd aliases

# alias a='fasd -a'        # any
# alias s='fasd -si'       # show / search / select
# alias d='fasd -d'        # directory
# alias f='fasd -f'        # file
# alias sd='fasd -sid'     # interactive directory selection
# alias sf='fasd -sif'     # interactive file selection
# alias z='z'     # cd, same functionality as j in autojump
# alias zz='fasd_cd -d -i' # cd with interactive selection
# alias v='f -e "$EDITOR"'
# alias o='a -e xdg-open'
# alias j='zz'

# run zoxide interactive then tmux in the selected dir
alias zt="zi && tmux"


# run zoxide interactive and then fuzzy find files in the selected dir then open selected file with $EDITOR
alias zd="zi && fe"


alias nvd='cd ~/.config/nvim/ && fe'
alias zshd='cd "$ZDOTDIR" && fe'
alias dotf='cd ~/dotfiles && fe'

